# Generated by Django 4.0.1 on 2023-01-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_invoice_payment_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
