# Generated by Django 4.0.1 on 2023-01-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_delete_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='card_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
