# Generated by Django 4.0.1 on 2023-01-11 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_invoice_card_no_invoice_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='cgst_no',
            new_name='customer_gst_no',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_no',
        ),
    ]
