# Generated by Django 4.0.1 on 2023-01-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_invoice_amount_in_words_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
