# Generated by Django 4.0.1 on 2023-01-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_delete_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_from', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('customer_gst_no', models.CharField(max_length=100, null=True)),
                ('gst_amount', models.IntegerField(null=True)),
                ('course_amount', models.IntegerField(null=True)),
                ('for_the_course_of', models.CharField(choices=[('Data science', 'Data Science'), ('Data Analysts', 'Data Analysts')], max_length=100, null=True)),
                ('payment_mode', models.CharField(choices=[('card', 'card'), ('cash', 'cash')], max_length=100, null=True)),
                ('card_no', models.IntegerField(null=True)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
