# Generated by Django 4.0.1 on 2023-01-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='for_the_course_of2',
            field=models.CharField(choices=[('Data science', 'Data Science'), ('Data Analysts', 'Data Analysts')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='for_the_course_of3',
            field=models.CharField(choices=[('Data science', 'Data Science'), ('Data Analysts', 'Data Analysts')], max_length=100, null=True),
        ),
    ]
