# Generated by Django 4.0.1 on 2023-01-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_receipt_amount_receipt_amount2_receipt_amount3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='card_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
