# Generated by Django 4.0.1 on 2023-01-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_receipt_card_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='card_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_mode',
            field=models.CharField(choices=[('card', 'card'), ('cash', 'cash'), ('cheque no', 'cheque no')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
