# Generated by Django 3.0.5 on 2023-01-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_receipt_cheque_no_alter_receipt_card_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='logo',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_mode',
            field=models.CharField(choices=[('Debit card', 'Debit card'), ('Credit card', 'Credit card'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Mobile Transaction', 'Mobile Transaction'), ('Electronic Bank Transfer', 'Electronic Bank Transfer')], max_length=100, null=True),
        ),
    ]
