# Generated by Django 3.0.5 on 2023-01-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20230117_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='customer_gst_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
