# Generated by Django 3.0.5 on 2023-01-20 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_invoiced_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiced_receipt',
            name='customer_gst_no',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoiced_customer_gst_no', to='app.Invoice'),
        ),
        migrations.AddField(
            model_name='invoiced_receipt',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiced_receipt',
            name='received_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoiced_receiver_name', to='app.Invoice'),
        ),
    ]
