# Generated by Django 3.0.5 on 2023-01-20 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20230120_0752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoiced_Receipt',
        ),
    ]
