# Generated by Django 3.0.5 on 2023-01-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_receipt_invoiceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='for_the_course_of3',
            field=models.CharField(blank=True, choices=[('Data science', 'Data Science'), ('Data Analysts', 'Data Analysts'), ('ML/AI ', 'ML/AI'), ('Cloud Computing ', 'Cloud Computing'), ('IOT', 'IOT'), ('Digital Marketing(SEO, SEM, SMO and SMM)', 'Digital Marketing(SEO, SEM, SMO and SMM)'), ('Web Development and Mobile App Development', 'Web Development and Mobile App Development'), ('Web Designing and Graphic Designing', 'Web Designing and Graphic Designing')], max_length=100, null=True),
        ),
    ]
